from enum import Enum


class OrderStatus(str, Enum):

    CREATED = "CREATED"

    ORDER_VALIDATED = "ORDER_VALIDATED"

    INVENTORY_VERIFIED = "INVENTORY_VERIFIED"

    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"

    APPROVED = "APPROVED"

    INVOICE_GENERATED = "INVOICE_GENERATED"

    FAILED = "FAILED"